openapi: 3.0.0
info:
  title: instant order backend API
  description: this is API
paths:
  /api/product:
    get:
      tags:
        - product
      responses:
        '200':
          content:
            application.json:
              schema:
                type: object